swagger: 2.0
InvoiceVo:
  descriptions: invoice data
  required:
    - id
    - invoiceNo
  properties:
    id:
      type: integer
      format: int64
    invoiceNo:
      type: string
Invoices:
  type: array
  items:
    $ref: "#InvoiceVo"
